apiVersion: v1
kind: ConfigMap
metadata:
  name: notes-config
  namespace: notes
data:
  APP_ENV: "local"
  LOG_LEVEL: "info"
  GREETING: "hello from kubernetes"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "notes"
  DB_POOL_MAX: "5"
